source 'https://github.com/lyleLH/MTSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'MTHTTPClient_Example' do
  pod 'MTHTTPClient', :path => '../'

  target 'MTHTTPClient_Tests' do
    inherit! :search_paths

    
  end
end
